### ISSUE TITLE
Panic on line 41

### ISSUE THREAD

**Issue by danepowell** [jerrywoo96/AddMissingHeaders#2]
Whenever a middleware using this plugin runs, it generates a panic in the Traefik logs:

> time="2022-12-30T16:01:39Z" level=error msg="plugins-storage/sources/gop-3601781398/src/github.com/jerrywoo96/AddMissingHeaders/addmissingheaders.go:41:26: panic" module=github.com/jerrywoo96/AddMissingHeaders plugin=plugin-AddMissingHeaders

There are some debug logs around that but I'm hesitant to post them as they have some sensitive info. Let me know if you need them.

Here's my middleware config:

```
    append-security-headers:
      plugin:
        AddMissingHeaders:
          responseHeaders:
            # headers: frameDeny can break apps that use frames such as pi-hole
            # @see https://github.com/traefik/traefik/issues/8808
            X-Frame-Options: DENY
```

I thought maybe the problem was that I hadn't defined any requestHeaders so I added the following, but it didn't help:
```
          requestHeaders:
            X-Custom-RequestHeader: CustomRequestHeader
```
